language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo

before_install:
  - sudo apt-get update
  - sudo apt-get -y install btrfs-progs
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt -- --check
  - cargo clippy --release -- -D warnings
  - cargo build -v --release
  - cargo build -v --release --examples
